name: swiftsell
description: "Swiftsell POS"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  http: any
  image_picker: ^1.0.4
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^11.2.0
  visibility_detector: ^0.4.0+2
  easy_debounce: ^2.0.3
  package_info_plus: ^8.0.0
  path: any
  path_provider: any
  file_picker: ^8.0.3
  get_it: ^7.7.0
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.3
  share_plus: ^9.0.0
  flutter_social_textfield: ^0.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_cached_pdfview: ^0.4.2
  device_info_plus: ^10.1.2
  wakelock_plus: ^1.2.8
  location: ^6.0.2
  email_validator: '^2.1.16'
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
